### ISSUE TITLE
I'm experiencing a bug in hyprbars

### ISSUE THREAD

**Issue by cilegordev** [hyprwm/hyprland-plugins#71]
![Screenshot_2024-01-13-13-50-06_13819](https://github.com/hyprwm/hyprland-plugins/assets/123652808/fe5705f7-91d6-45aa-b8c7-9efa0565062e)

when I open discord via tray bars will increase as more are opened. and when I try to disable hyprbars then reopen discord via tray without rebooting then the hyprland session will be forced to close.

**Comment by fclivaz42** [comment]
This seems to be an issue with WebCord too by the way.
![image](https://github.com/hyprwm/hyprland-plugins/assets/95506988/f59330b0-12b2-4aa4-b72d-83389b3bd017)

In other words, everytime WebCord or Discord is closed and opened again, Hyprbars decides to draw an extra bar on top.
![image](https://github.com/hyprwm/hyprland-plugins/assets/95506988/dceb5e90-26bb-4b5d-b873-275bd89edcd9)

I tried replicating this with another Electron app (VSCode), but it worked as intended. 

A quick ps -ax shows that webcord and discord dont seem to close properly?

![image](https://github.com/hyprwm/hyprland-plugins/assets/95506988/6a0ee5bc-041e-43db-a929-1c29a9f20b91)

![image](https://github.com/hyprwm/hyprland-plugins/assets/95506988/ab4563cc-ca88-4517-938e-76b3b4db4fe4)


After a quick killall Discord and killall Webcord, the issue seems to be fixed, however. So I guess Hyprland isnt terminating those processes correctly?

**Comment by GG2R10** [comment]
It's a problem with all programs that minimize to tray, im having the same issue with steam:
![image](https://github.com/hyprwm/hyprland-plugins/assets/114362342/0b78cde3-423d-47f1-a66f-2bb4957f88e3)

**Comment by dachinat** [comment]
Any solution? I'm having the same problem.
![Uploading 2024-03-21-223737_hyprshot.png…]()

**Comment by vaxerski** [comment]
the solution is either bugging me enough to fix it, bribery, or fixing it yourself and making a pr
