### ISSUE TITLE
Everything fails to build

### ISSUE THREAD

**Issue by exoess** [hyprwm/hyprland-plugins#85]
I just updated now nothing builds

**Comment by vaxerski** [comment]
plugins always chase -git

**Comment by exoess** [comment]
i am using -git

**Comment by vaxerski** [comment]
prove it by posting `hyprctl version`

**Comment by exoess** [comment]
Hyprland, built from branch main at commit 7e8bcd675de15ee2498f1aa15c5b335e9a9a55f0 dirty (monitors: fix outputmgr nullptr crash (4738)).
Date: Sat Feb 17 18:24:01 2024
Tag: v0.35.0-45-g7e8bcd67

**Comment by vaxerski** [comment]
see you're the dumb dumb here

<https://github.com/hyprwm/hyprland/commit/7e8bcd675de15ee2498f1aa15c5b335e9a9a55f0>

that's 2 days old, not -git :)

You know how much has changed since then?

![image](https://github.com/hyprwm/hyprland-plugins/assets/43317083/8a447601-64d4-4ccf-8c21-df4953138518)

a fucking lot.

Now go update and stop bug report

**Comment by exoess** [comment]
the fuck, i just ran `yay -Syu` or `yay --devel`
